/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 票台信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgencyType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "agencyID", "agencyCode", "cityID", "cityCode"})
@SuppressWarnings("all")
public class AgencyType implements Serializable {

    private static final long serialVersionUID = 1L;

    public AgencyType(int agencyID, String agencyCode, int cityID, String cityCode) {
        this.agencyID = agencyID;
        this.agencyCode = agencyCode;
        this.cityID = cityID;
        this.cityCode = cityCode;
    }

    public AgencyType() {
    }

    @JsonProperty("AgencyID")
    @XmlElement(name = "AgencyID")
    private int agencyID;

    @JsonProperty("AgencyCode")
    @XmlElement(name = "AgencyCode")
    private String agencyCode;

    @JsonProperty("CityID")
    @XmlElement(name = "CityID")
    private int cityID;

    @JsonProperty("CityCode")
    @XmlElement(name = "CityCode")
    private String cityCode;

    /**
     * *票台ID
     */
    public int getAgencyID() {
        return this.agencyID;
    }

    public void setAgencyID(int agencyID) {
        this.agencyID = agencyID;
    }

    /**
     * *票台代码
     */
    public String getAgencyCode() {
        return this.agencyCode;
    }

    public void setAgencyCode(String agencyCode) {
        this.agencyCode = agencyCode;
    }

    /**
     * 城市ID
     */
    public int getCityID() {
        return this.cityID;
    }

    public void setCityID(int cityID) {
        this.cityID = cityID;
    }

    /**
     * 城市代码
     */
    public String getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final AgencyType other = (AgencyType) obj;
        return Objects.equal(this.agencyID, other.agencyID) && Objects.equal(this.agencyCode, other.agencyCode)
            && Objects.equal(this.cityID, other.cityID) && Objects.equal(this.cityCode, other.cityCode);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.agencyID);
        result = 31 * result + Objects.hashCode(this.agencyCode);
        result = 31 * result + Objects.hashCode(this.cityID);
        result = 31 * result + Objects.hashCode(this.cityCode);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("agencyID", agencyID).add("agencyCode", agencyCode)
            .add("cityID", cityID).add("cityCode", cityCode).toString();
    }

}