/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 行李额
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaggageDetailType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "amount", "unit", "type"})
@SuppressWarnings("all")
public class BaggageDetailType implements Serializable {

    private static final long serialVersionUID = 1L;

    public BaggageDetailType(int amount, String unit, String type) {
        this.amount = amount;
        this.unit = unit;
        this.type = type;
    }

    public BaggageDetailType() {
    }

    @JsonProperty("Amount")
    @XmlElement(name = "Amount")
    private int amount;

    @JsonProperty("Unit")
    @XmlElement(name = "Unit")
    private String unit;

    @JsonProperty("Type")
    @XmlElement(name = "Type")
    private String type;

    /**
     * 数量
     */
    public int getAmount() {
        return this.amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     * 数量单位
     */
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * 单位标识
     */
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final BaggageDetailType other = (BaggageDetailType) obj;
        return Objects.equal(this.amount, other.amount) && Objects.equal(this.unit, other.unit) && Objects
            .equal(this.type, other.type);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.amount);
        result = 31 * result + Objects.hashCode(this.unit);
        result = 31 * result + Objects.hashCode(this.type);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("amount", amount).add("unit", unit).add("type", type).toString();
    }

}