/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * 综合Tag信息
 */

public class BaseTagInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public BaseTagInfoType(List<TagType> flightProductGroupTagList, List<TagType> searchResultTagList) {
        this.flightProductGroupTagList = flightProductGroupTagList;
        this.searchResultTagList = searchResultTagList;
    }

    public BaseTagInfoType() {
    }

    @JsonProperty("FlightProductGroupTagList")
    @XmlElement(name = "Tag")
    @XmlElementWrapper(name = "FlightProductGroupTagList")
    private List<TagType> flightProductGroupTagList;

    @JsonProperty("SearchResultTagList")
    @XmlElement(name = "Tag")
    @XmlElementWrapper(name = "SearchResultTagList")
    private List<TagType> searchResultTagList;

    /**
     * FlightProductGroup.TagList【ItineraryKey】
     */
    public List<TagType> getFlightProductGroupTagList() {
        return this.flightProductGroupTagList;
    }

    public void setFlightProductGroupTagList(List<TagType> flightProductGroupTagList) {
        this.flightProductGroupTagList = flightProductGroupTagList;
    }

    /**
     * SearchResult.TagList【SessionId/SearchId】【作用整个查询结果】
     */
    public List<TagType> getSearchResultTagList() {
        return this.searchResultTagList;
    }

    public void setSearchResultTagList(List<TagType> searchResultTagList) {
        this.searchResultTagList = searchResultTagList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final BaseTagInfoType other = (BaseTagInfoType) obj;
        return Objects.equal(this.flightProductGroupTagList, other.flightProductGroupTagList) && Objects
            .equal(this.searchResultTagList, other.searchResultTagList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.flightProductGroupTagList);
        result = 31 * result + Objects.hashCode(this.searchResultTagList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("flightProductGroupTagList", flightProductGroupTagList)
            .add("searchResultTagList", searchResultTagList).toString();
    }

}