/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;


public class BasePriceUnitType implements Serializable {

    private static final long serialVersionUID = 1L;

    public BasePriceUnitType(String bookingChannel, List<TagType> tagList) {
        this.bookingChannel = bookingChannel;
        this.tagList = tagList;
    }

    public BasePriceUnitType() {
    }

    @JsonProperty("BookingChannel")
    @XmlElement(name = "BookingChannel")
    private String bookingChannel;

    @JsonProperty("TagList")
    @XmlElement(name = "Tag")
    @XmlElementWrapper(name = "TagList")
    private List<TagType> tagList;

    /**
     * 预定渠道
     */
    public String getBookingChannel() {
        return this.bookingChannel;
    }

    public void setBookingChannel(String bookingChannel) {
        this.bookingChannel = bookingChannel;
    }

    /**
     * 用于存放一些和统计相关的非业务字段
     */
    public List<TagType> getTagList() {
        return this.tagList;
    }

    public void setTagList(List<TagType> tagList) {
        this.tagList = tagList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final BasePriceUnitType other = (BasePriceUnitType) obj;
        return Objects.equal(this.bookingChannel, other.bookingChannel) && Objects.equal(this.tagList, other.tagList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.bookingChannel);
        result = 31 * result + Objects.hashCode(this.tagList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("bookingChannel", bookingChannel).add("tagList", tagList)
            .toString();
    }

}