/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * 乘客信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({ReservationPassengerInfoType.class})
@XmlType(name = "BasePassengerInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "passengerId", "travelerCategoryCode", "birthDay", "gender", "nationalityCode", "mobilePhone",
    "mobilePhoneCountryCode", "idCardList"})
@SuppressWarnings("all")
public class BasePassengerInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public BasePassengerInfoType(int passengerId, TravelerCategoryCodeEnum travelerCategoryCode, String birthDay,
        GenderEnum gender, String nationalityCode, String mobilePhone, String mobilePhoneCountryCode,
        List<IDCardInfoType> idCardList) {
        this.passengerId = passengerId;
        this.travelerCategoryCode = travelerCategoryCode;
        this.birthDay = birthDay;
        this.gender = gender;
        this.nationalityCode = nationalityCode;
        this.mobilePhone = mobilePhone;
        this.mobilePhoneCountryCode = mobilePhoneCountryCode;
        this.idCardList = idCardList;
    }

    public BasePassengerInfoType() {
        this.travelerCategoryCode = TravelerCategoryCodeEnum.values()[0];
        this.gender = GenderEnum.values()[0];
    }

    @JsonProperty("PassengerId")
    @XmlElement(name = "PassengerId")
    private int passengerId;

    @JsonProperty("TravelerCategoryCode")
    @XmlElement(name = "TravelerCategoryCode")
    private TravelerCategoryCodeEnum travelerCategoryCode;

    @JsonProperty("BirthDay")
    @XmlElement(name = "BirthDay")
    private String birthDay;

    @JsonProperty("Gender")
    @XmlElement(name = "Gender")
    private GenderEnum gender;

    @JsonProperty("NationalityCode")
    @XmlElement(name = "NationalityCode")
    private String nationalityCode;

    @JsonProperty("MobilePhone")
    @XmlElement(name = "MobilePhone")
    private String mobilePhone;

    @JsonProperty("MobilePhoneCountryCode")
    @XmlElement(name = "MobilePhoneCountryCode")
    private String mobilePhoneCountryCode;

    @JsonProperty("IDCardList")
    @XmlElement(name = "IDCardInfo")
    @XmlElementWrapper(name = "IDCardList")
    private List<IDCardInfoType> idCardList;

    /**
     * 乘客ID，用于获取X产品
     */
    public int getPassengerId() {
        return this.passengerId;
    }

    public void setPassengerId(int passengerId) {
        this.passengerId = passengerId;
    }

    /**
     * 乘客类型
     */
    public TravelerCategoryCodeEnum getTravelerCategoryCode() {
        return this.travelerCategoryCode;
    }

    public void setTravelerCategoryCode(TravelerCategoryCodeEnum travelerCategoryCode) {
        this.travelerCategoryCode = travelerCategoryCode;
    }

    /**
     * 乘客出生日期 pattern: yyyy-MM-dd
     */
    public String getBirthDay() {
        return this.birthDay;
    }

    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * 性别
     */
    public GenderEnum getGender() {
        return this.gender;
    }

    public void setGender(GenderEnum gender) {
        this.gender = gender;
    }

    /**
     * 国籍
     */
    public String getNationalityCode() {
        return this.nationalityCode;
    }

    public void setNationalityCode(String nationalityCode) {
        this.nationalityCode = nationalityCode;
    }

    /**
     * 手机号码
     */
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * 乘机人手机国家码
     */
    public String getMobilePhoneCountryCode() {
        return this.mobilePhoneCountryCode;
    }

    public void setMobilePhoneCountryCode(String mobilePhoneCountryCode) {
        this.mobilePhoneCountryCode = mobilePhoneCountryCode;
    }

    /**
     * 证件信息列表
     */
    public List<IDCardInfoType> getIdCardList() {
        return this.idCardList;
    }

    public void setIdCardList(List<IDCardInfoType> idCardList) {
        this.idCardList = idCardList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final BasePassengerInfoType other = (BasePassengerInfoType) obj;
        return Objects.equal(this.passengerId, other.passengerId) && Objects
            .equal(this.travelerCategoryCode, other.travelerCategoryCode) && Objects
            .equal(this.birthDay, other.birthDay) && Objects.equal(this.gender, other.gender) && Objects
            .equal(this.nationalityCode, other.nationalityCode) && Objects.equal(this.mobilePhone, other.mobilePhone)
            && Objects.equal(this.mobilePhoneCountryCode, other.mobilePhoneCountryCode) && Objects
            .equal(this.idCardList, other.idCardList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.passengerId);
        result = 31 * result + Objects.hashCode(this.travelerCategoryCode);
        result = 31 * result + Objects.hashCode(this.birthDay);
        result = 31 * result + Objects.hashCode(this.gender);
        result = 31 * result + Objects.hashCode(this.nationalityCode);
        result = 31 * result + Objects.hashCode(this.mobilePhone);
        result = 31 * result + Objects.hashCode(this.mobilePhoneCountryCode);
        result = 31 * result + Objects.hashCode(this.idCardList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("passengerId", passengerId)
            .add("travelerCategoryCode", travelerCategoryCode).add("birthDay", birthDay).add("gender", gender)
            .add("nationalityCode", nationalityCode).add("mobilePhone", mobilePhone)
            .add("mobilePhoneCountryCode", mobilePhoneCountryCode).add("idCardList", idCardList).toString();
    }

}