// Generated by eBay Common SDK Platform
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * 舱等
 */
@XmlType(name = "CabinClassEnumType")
@XmlEnum
@SuppressWarnings("all")
public enum CabinClassEnumType {

    /**
     * Economy 经济舱
     */
    @XmlEnumValue("Y") Y(0, "Y"),

    /**
     * Premium 超经舱 联程、缺口程等特殊舱位 S改成国际标准W
     */
    @XmlEnumValue("W") W(1, "W"),

    /**
     * Business 商务舱
     */
    @XmlEnumValue("C") C(2, "C"),

    /**
     * First 头等舱
     */
    @XmlEnumValue("F") F(3, "F");

    private final int intValue;
    private final String value;

    CabinClassEnumType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static CabinClassEnumType fromValue(String v) {
        for (CabinClassEnumType e : CabinClassEnumType.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static CabinClassEnumType findByValue(int value) {
        switch (value) {
            case 0:
                return Y;
            case 1:
                return W;
            case 2:
                return C;
            case 3:
                return F;
            default:
                return null;
        }
    }
}