// Generated by eBay Common SDK Platform
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * 用来区分不同客户端
 */
@XmlType(name = "ChannelIDEnum")
@XmlEnum
@SuppressWarnings("all")
public enum ChannelIDEnum {

    /**
     * NONE
     */
    @XmlEnumValue("NONE") NONE(0, "NONE"),

    /**
     * 国内机票online
     */
    @XmlEnumValue("FlightOnline") FlightOnline(1, "FlightOnline"),

    /**
     * 国内机票offline
     */
    @XmlEnumValue("FlightOffline") FlightOffline(2, "FlightOffline"),

    /**
     * 国内机票对外接口
     */
    @XmlEnumValue("FlightExternal") FlightExternal(3, "FlightExternal"),

    /**
     * 国际机票online
     */
    @XmlEnumValue("FlightIntlOnline") FlightIntlOnline(4, "FlightIntlOnline"),

    /**
     * 国际机票offline
     */
    @XmlEnumValue("FlightIntlOffline") FlightIntlOffline(5, "FlightIntlOffline"),

    /**
     * 国际机票对外接口
     */
    @XmlEnumValue("FltIntlExternal") FltIntlExternal(6, "FltIntlExternal"),

    /**
     * online SEO
     */
    @XmlEnumValue("FlightIntlOnlineSEO") FlightIntlOnlineSEO(7, "FlightIntlOnlineSEO"),

    /**
     * 商旅 online
     */
    @XmlEnumValue("Corporation") Corporation(8, "Corporation"),

    /**
     * 商旅 offline
     */
    @XmlEnumValue("CorpOffline") CorpOffline(9, "CorpOffline"),

    /**
     * 商旅 mobile
     */
    @XmlEnumValue("CorpMobile") CorpMobile(10, "CorpMobile"),

    /**
     * 度假
     */
    @XmlEnumValue("Vacation") Vacation(11, "Vacation"),

    /**
     * 度假团队
     */
    @XmlEnumValue("VacationGroup") VacationGroup(12, "VacationGroup"),

    /**
     * 度假指定PolicyCode的查询渠道
     */
    @XmlEnumValue("RestrictedVacation") RestrictedVacation(13, "RestrictedVacation"),

    /**
     * 度假自由行
     */
    @XmlEnumValue("FitTravel") FitTravel(14, "FitTravel"),

    /**
     * 无线APP
     */
    @XmlEnumValue("Mobile") Mobile(15, "Mobile"),

    /**
     * 无线H5
     */
    @XmlEnumValue("MobileH5") MobileH5(16, "MobileH5"),

    /**
     * 酒店
     */
    @XmlEnumValue("Hotel") Hotel(17, "Hotel"),

    /**
     * 国内机酒
     */
    @XmlEnumValue("AirHotel") AirHotel(18, "AirHotel"),

    /**
     * 国际机酒
     */
    @XmlEnumValue("AirHotelIntl") AirHotelIntl(19, "AirHotelIntl"),

    /**
     * 新机+酒
     */
    @XmlEnumValue("AirHotelIntlEx") AirHotelIntlEx(20, "AirHotelIntlEx"),

    /**
     * 机酒套餐
     */
    @XmlEnumValue("AirHotelPackage") AirHotelPackage(21, "AirHotelPackage"),

    /**
     * 英文子系统
     */
    @XmlEnumValue("EnglishSite") EnglishSite(22, "EnglishSite"),

    /**
     * 高铁
     */
    @XmlEnumValue("HighRail") HighRail(23, "HighRail"),

    /**
     * 分销联盟
     */
    @XmlEnumValue("Affiliate") Affiliate(24, "Affiliate"),

    /**
     * 高端旅游
     */
    @XmlEnumValue("Luxury") Luxury(25, "Luxury"),

    /**
     * 客服
     */
    @XmlEnumValue("Customer") Customer(26, "Customer"),

    /**
     * MICE子系统
     */
    @XmlEnumValue("Mice") Mice(27, "Mice"),

    /**
     * 社区攻略
     */
    @XmlEnumValue("Community") Community(28, "Community"),

    /**
     * 易游网
     */
    @XmlEnumValue("EzTravel") EzTravel(29, "EzTravel"),

    /**
     * 永安
     */
    @XmlEnumValue("Wingon") Wingon(30, "Wingon"),

    /**
     * 分销联盟
     */
    @XmlEnumValue("Distribution") Distribution(31, "Distribution"),

    /**
     * BI 统计
     */
    @XmlEnumValue("BIChannel") BIChannel(32, "BIChannel"),

    /**
     * 金融渠道
     */
    @XmlEnumValue("Finance") Finance(33, "Finance"),

    /**
     * 确认客户
     */
    @XmlEnumValue("ConfirmCustomer") ConfirmCustomer(34, "ConfirmCustomer"),

    /**
     * 香港站
     */
    @XmlEnumValue("HKSite") HKSite(35, "HKSite"),

    /**
     * 韩国站
     */
    @XmlEnumValue("KRSite") KRSite(36, "KRSite"),

    /**
     * 日本站
     */
    @XmlEnumValue("JPSite") JPSite(37, "JPSite"),

    /**
     * 新加坡站
     */
    @XmlEnumValue("SGSite") SGSite(38, "SGSite"),

    /**
     * 台湾站
     */
    @XmlEnumValue("TWSite") TWSite(39, "TWSite"),

    /**
     * 泰国站
     */
    @XmlEnumValue("THSite") THSite(40, "THSite"),

    /**
     * 去哪儿
     */
    @XmlEnumValue("Qunar") Qunar(41, "Qunar"),

    /**
     * Skyscanner
     */
    @XmlEnumValue("Skyscanner") Skyscanner(42, "Skyscanner");

    private final int intValue;
    private final String value;

    ChannelIDEnum(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static ChannelIDEnum fromValue(String v) {
        for (ChannelIDEnum e : ChannelIDEnum.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static ChannelIDEnum findByValue(int value) {
        switch (value) {
            case 0:
                return NONE;
            case 1:
                return FlightOnline;
            case 2:
                return FlightOffline;
            case 3:
                return FlightExternal;
            case 4:
                return FlightIntlOnline;
            case 5:
                return FlightIntlOffline;
            case 6:
                return FltIntlExternal;
            case 7:
                return FlightIntlOnlineSEO;
            case 8:
                return Corporation;
            case 9:
                return CorpOffline;
            case 10:
                return CorpMobile;
            case 11:
                return Vacation;
            case 12:
                return VacationGroup;
            case 13:
                return RestrictedVacation;
            case 14:
                return FitTravel;
            case 15:
                return Mobile;
            case 16:
                return MobileH5;
            case 17:
                return Hotel;
            case 18:
                return AirHotel;
            case 19:
                return AirHotelIntl;
            case 20:
                return AirHotelIntlEx;
            case 21:
                return AirHotelPackage;
            case 22:
                return EnglishSite;
            case 23:
                return HighRail;
            case 24:
                return Affiliate;
            case 25:
                return Luxury;
            case 26:
                return Customer;
            case 27:
                return Mice;
            case 28:
                return Community;
            case 29:
                return EzTravel;
            case 30:
                return Wingon;
            case 31:
                return Distribution;
            case 32:
                return BIChannel;
            case 33:
                return Finance;
            case 34:
                return ConfirmCustomer;
            case 35:
                return HKSite;
            case 36:
                return KRSite;
            case 37:
                return JPSite;
            case 38:
                return SGSite;
            case 39:
                return TWSite;
            case 40:
                return THSite;
            case 41:
                return Qunar;
            case 42:
                return Skyscanner;
            default:
                return null;
        }
    }
}