/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 身份证件相关信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IDCardInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "priceUnitIndex", "passengerCardId", "surName", "givenName", "fullNameRemark", "idCardType", "idCardNo",
    "cardTimeLimit", "issuingCountry"})
@SuppressWarnings("all")
public class IDCardInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public IDCardInfoType(int priceUnitIndex, int passengerCardId, String surName, String givenName,
        String fullNameRemark, String idCardType, String idCardNo, String cardTimeLimit, String issuingCountry) {
        this.priceUnitIndex = priceUnitIndex;
        this.passengerCardId = passengerCardId;
        this.surName = surName;
        this.givenName = givenName;
        this.fullNameRemark = fullNameRemark;
        this.idCardType = idCardType;
        this.idCardNo = idCardNo;
        this.cardTimeLimit = cardTimeLimit;
        this.issuingCountry = issuingCountry;
    }

    public IDCardInfoType() {
    }

    @JsonProperty("PriceUnitIndex")
    @XmlElement(name = "PriceUnitIndex")
    private int priceUnitIndex;

    @JsonProperty("PassengerCardId")
    @XmlElement(name = "PassengerCardId")
    private int passengerCardId;

    @JsonProperty("SurName")
    @XmlElement(name = "SurName")
    private String surName;

    @JsonProperty("GivenName")
    @XmlElement(name = "GivenName")
    private String givenName;

    @JsonProperty("FullNameRemark")
    @XmlElement(name = "FullNameRemark")
    private String fullNameRemark;

    @JsonProperty("IDCardType")
    @XmlElement(name = "IDCardType")
    private String idCardType;

    @JsonProperty("IDCardNo")
    @XmlElement(name = "IDCardNo")
    private String idCardNo;

    @JsonProperty("CardTimeLimit")
    @XmlElement(name = "CardTimeLimit")
    private String cardTimeLimit;

    @JsonProperty("IssuingCountry")
    @XmlElement(name = "IssuingCountry")
    private String issuingCountry;

    /**
     * PU索引
     */
    public int getPriceUnitIndex() {
        return this.priceUnitIndex;
    }

    public void setPriceUnitIndex(int priceUnitIndex) {
        this.priceUnitIndex = priceUnitIndex;
    }

    /**
     * 乘客证件Id，订位X产品需要
     */
    public int getPassengerCardId() {
        return this.passengerCardId;
    }

    public void setPassengerCardId(int passengerCardId) {
        this.passengerCardId = passengerCardId;
    }

    /**
     * 乘客的姓
     */
    public String getSurName() {
        return this.surName;
    }

    public void setSurName(String surName) {
        this.surName = surName;
    }

    /**
     * 乘客的名
     */
    public String getGivenName() {
        return this.givenName;
    }

    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    /**
     * 乘客姓名全称备注 订位使用
     */
    public String getFullNameRemark() {
        return this.fullNameRemark;
    }

    public void setFullNameRemark(String fullNameRemark) {
        this.fullNameRemark = fullNameRemark;
    }

    /**
     * *证件类型
     */
    public String getIdCardType() {
        return this.idCardType;
    }

    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * *证件号
     */
    public String getIdCardNo() {
        return this.idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * 证件有效期 pattern: yyyy-MM-dd
     */
    public String getCardTimeLimit() {
        return this.cardTimeLimit;
    }

    public void setCardTimeLimit(String cardTimeLimit) {
        this.cardTimeLimit = cardTimeLimit;
    }

    /**
     * 发证国家
     */
    public String getIssuingCountry() {
        return this.issuingCountry;
    }

    public void setIssuingCountry(String issuingCountry) {
        this.issuingCountry = issuingCountry;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final IDCardInfoType other = (IDCardInfoType) obj;
        return Objects.equal(this.priceUnitIndex, other.priceUnitIndex) && Objects
            .equal(this.passengerCardId, other.passengerCardId) && Objects.equal(this.surName, other.surName) && Objects
            .equal(this.givenName, other.givenName) && Objects.equal(this.fullNameRemark, other.fullNameRemark)
            && Objects.equal(this.idCardType, other.idCardType) && Objects.equal(this.idCardNo, other.idCardNo)
            && Objects.equal(this.cardTimeLimit, other.cardTimeLimit) && Objects
            .equal(this.issuingCountry, other.issuingCountry);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.priceUnitIndex);
        result = 31 * result + Objects.hashCode(this.passengerCardId);
        result = 31 * result + Objects.hashCode(this.surName);
        result = 31 * result + Objects.hashCode(this.givenName);
        result = 31 * result + Objects.hashCode(this.fullNameRemark);
        result = 31 * result + Objects.hashCode(this.idCardType);
        result = 31 * result + Objects.hashCode(this.idCardNo);
        result = 31 * result + Objects.hashCode(this.cardTimeLimit);
        result = 31 * result + Objects.hashCode(this.issuingCountry);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("priceUnitIndex", priceUnitIndex)
            .add("passengerCardId", passengerCardId).add("surName", surName).add("givenName", givenName)
            .add("fullNameRemark", fullNameRemark).add("idCardType", idCardType).add("idCardNo", idCardNo)
            .add("cardTimeLimit", cardTimeLimit).add("issuingCountry", issuingCountry).toString();
    }

}