/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 此类型包含的参数不应该在业务逻辑中使用，这些参数是用来跟踪调试，查找特定用户特定操作等目的。
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestHeaderType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "loggingLevel"})
@SuppressWarnings("all")
public class RequestHeaderType extends MessageHeaderType implements Serializable {

    private static final long serialVersionUID = 1L;

    public RequestHeaderType(int loggingLevel) {
        this.loggingLevel = loggingLevel;
    }

    public RequestHeaderType() {
    }

    @JsonProperty("LoggingLevel")
    @XmlElement(name = "LoggingLevel")
    private int loggingLevel;

    /**
     * 用于LoggingLevel用来控制应用服务内部处理此报文的日志或记录，0表示不需要任何日志或记录，1表示必要的日志或记录，etc（注意：每个应用服务可以自由定义各值的含义）
     */
    public int getLoggingLevel() {
        return this.loggingLevel;
    }

    public void setLoggingLevel(int loggingLevel) {
        this.loggingLevel = loggingLevel;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final RequestHeaderType other = (RequestHeaderType) obj;
        return Objects.equal(this.loggingLevel, other.loggingLevel);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.loggingLevel);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("loggingLevel", loggingLevel).toString();
    }

}