/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * 订位乘客信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationPassengerInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "ffpNoList"})
@SuppressWarnings("all")
public class ReservationPassengerInfoType extends BasePassengerInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ReservationPassengerInfoType(List<FFPNoInfoType> ffpNoList) {
        this.ffpNoList = ffpNoList;
    }

    public ReservationPassengerInfoType() {
    }

    @JsonProperty("FFPNoList")
    @XmlElement(name = "FFPNoInfo")
    @XmlElementWrapper(name = "FFPNoList")
    private List<FFPNoInfoType> ffpNoList;

    /**
     * 常旅客信息列表 Frequent flyer
     */
    public List<FFPNoInfoType> getFfpNoList() {
        return this.ffpNoList;
    }

    public void setFfpNoList(List<FFPNoInfoType> ffpNoList) {
        this.ffpNoList = ffpNoList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final ReservationPassengerInfoType other = (ReservationPassengerInfoType) obj;
        return Objects.equal(this.ffpNoList, other.ffpNoList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.ffpNoList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("ffpNoList", ffpNoList).toString();
    }

}