/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 订位后运价信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationFareInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "eligibility", "passengerType", "currency", "publishPrice", "tax"})
@SuppressWarnings("all")
public class ReservationFareInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ReservationFareInfoType(String eligibility, String passengerType, String currency, double publishPrice,
        double tax) {
        this.eligibility = eligibility;
        this.passengerType = passengerType;
        this.currency = currency;
        this.publishPrice = publishPrice;
        this.tax = tax;
    }

    public ReservationFareInfoType() {
    }

    @JsonProperty("Eligibility")
    @XmlElement(name = "Eligibility")
    private String eligibility;

    @JsonProperty("PassengerType")
    @XmlElement(name = "PassengerType")
    private String passengerType;

    @JsonProperty("Currency")
    @XmlElement(name = "Currency")
    private String currency;

    @JsonProperty("PublishPrice")
    @XmlElement(name = "PublishPrice")
    private double publishPrice;

    @JsonProperty("Tax")
    @XmlElement(name = "Tax")
    private double tax;

    /**
     * 乘客资质
     */
    public String getEligibility() {
        return this.eligibility;
    }

    public void setEligibility(String eligibility) {
        this.eligibility = eligibility;
    }

    /**
     * 乘客类型 ADT/CHD/INF
     */
    public String getPassengerType() {
        return this.passengerType;
    }

    public void setPassengerType(String passengerType) {
        this.passengerType = passengerType;
    }

    /**
     * 票台结算币种
     */
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * 航司票台公布价
     */
    public double getPublishPrice() {
        return this.publishPrice;
    }

    public void setPublishPrice(double publishPrice) {
        this.publishPrice = publishPrice;
    }

    /**
     * 航司票台税费
     */
    public double getTax() {
        return this.tax;
    }

    public void setTax(double tax) {
        this.tax = tax;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final ReservationFareInfoType other = (ReservationFareInfoType) obj;
        return Objects.equal(this.eligibility, other.eligibility) && Objects
            .equal(this.passengerType, other.passengerType) && Objects.equal(this.currency, other.currency) && Objects
            .equal(this.publishPrice, other.publishPrice) && Objects.equal(this.tax, other.tax);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.eligibility);
        result = 31 * result + Objects.hashCode(this.passengerType);
        result = 31 * result + Objects.hashCode(this.currency);
        result = 31 * result + Objects.hashCode(this.publishPrice);
        result = 31 * result + Objects.hashCode(this.tax);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("eligibility", eligibility).add("passengerType", passengerType)
            .add("currency", currency).add("publishPrice", publishPrice).add("tax", tax).toString();
    }

}