/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * 订位结果信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationResultType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "airlineOrderID", "recordNo", "officeNumber", "reservationFareList"})
@SuppressWarnings("all")
public class ReservationResultType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ReservationResultType(String airlineOrderID, String recordNo, String officeNumber,
        List<ReservationFareInfoType> reservationFareList) {
        this.airlineOrderID = airlineOrderID;
        this.recordNo = recordNo;
        this.officeNumber = officeNumber;
        this.reservationFareList = reservationFareList;
    }

    public ReservationResultType() {
    }

    @JsonProperty("AirlineOrderID")
    @XmlElement(name = "AirlineOrderID")
    private String airlineOrderID;

    @JsonProperty("RecordNo")
    @XmlElement(name = "RecordNo")
    private String recordNo;

    @JsonProperty("OfficeNumber")
    @XmlElement(name = "OfficeNumber")
    private String officeNumber;

    @JsonProperty("ReservationFareList")
    @XmlElement(name = "ReservationFareInfo")
    @XmlElementWrapper(name = "ReservationFareList")
    private List<ReservationFareInfoType> reservationFareList;

    /**
     * 航空公司订单号
     */
    public String getAirlineOrderID() {
        return this.airlineOrderID;
    }

    public void setAirlineOrderID(String airlineOrderID) {
        this.airlineOrderID = airlineOrderID;
    }

    /**
     * 航空公司记录编号
     */
    public String getRecordNo() {
        return this.recordNo;
    }

    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    /**
     * OfficeNumber
     */
    public String getOfficeNumber() {
        return this.officeNumber;
    }

    public void setOfficeNumber(String officeNumber) {
        this.officeNumber = officeNumber;
    }

    /**
     * 订位后运价信息集合
     */
    public List<ReservationFareInfoType> getReservationFareList() {
        return this.reservationFareList;
    }

    public void setReservationFareList(List<ReservationFareInfoType> reservationFareList) {
        this.reservationFareList = reservationFareList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final ReservationResultType other = (ReservationResultType) obj;
        return Objects.equal(this.airlineOrderID, other.airlineOrderID) && Objects.equal(this.recordNo, other.recordNo)
            && Objects.equal(this.officeNumber, other.officeNumber) && Objects
            .equal(this.reservationFareList, other.reservationFareList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.airlineOrderID);
        result = 31 * result + Objects.hashCode(this.recordNo);
        result = 31 * result + Objects.hashCode(this.officeNumber);
        result = 31 * result + Objects.hashCode(this.reservationFareList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("airlineOrderID", airlineOrderID).add("recordNo", recordNo)
            .add("officeNumber", officeNumber).add("reservationFareList", reservationFareList).toString();
    }

}