/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseHeaderType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "serverIP", "returnCode"})
@SuppressWarnings("all")
public class ResponseHeaderType extends MessageHeaderType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ResponseHeaderType(String serverIP, int returnCode) {
        this.serverIP = serverIP;
        this.returnCode = returnCode;
    }

    public ResponseHeaderType() {
    }

    @JsonProperty("ServerIP")
    @XmlElement(name = "ServerIP")
    private String serverIP;

    @JsonProperty("ReturnCode")
    @XmlElement(name = "ReturnCode")
    private int returnCode;

    /**
     * 用来标识应用服务器的IP地址
     */
    public String getServerIP() {
        return this.serverIP;
    }

    public void setServerIP(String serverIP) {
        this.serverIP = serverIP;
    }

    /**
     * 用处理结果标识：0-无错，其他为错误代码（注意：每个应用服务可以自由定义什么是出错）
     */
    public int getReturnCode() {
        return this.returnCode;
    }

    public void setReturnCode(int returnCode) {
        this.returnCode = returnCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final ResponseHeaderType other = (ResponseHeaderType) obj;
        return Objects.equal(this.serverIP, other.serverIP) && Objects.equal(this.returnCode, other.returnCode);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.serverIP);
        result = 31 * result + Objects.hashCode(this.returnCode);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("serverIP", serverIP).add("returnCode", returnCode).toString();
    }

}