/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 经停信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1", propOrder = {
    "airport", "duration", "arrivalDateTime"})
@SuppressWarnings("all")
public class StopType implements Serializable {

    private static final long serialVersionUID = 1L;

    public StopType(String airport, String duration, String arrivalDateTime) {
        this.airport = airport;
        this.duration = duration;
        this.arrivalDateTime = arrivalDateTime;
    }

    public StopType() {
    }

    @JsonProperty("Airport")
    @XmlElement(name = "Airport")
    private String airport;

    @JsonProperty("Duration")
    @XmlElement(name = "Duration")
    private String duration;

    @JsonProperty("ArrivalDateTime")
    @XmlElement(name = "ArrivalDateTime")
    private String arrivalDateTime;

    /**
     * 经停机场
     */
    public String getAirport() {
        return this.airport;
    }

    public void setAirport(String airport) {
        this.airport = airport;
    }

    /**
     * 经停时长
     */
    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * 到达时间 pattern: yyyy-MM-dd HH:mm:ss
     */
    public String getArrivalDateTime() {
        return this.arrivalDateTime;
    }

    public void setArrivalDateTime(String arrivalDateTime) {
        this.arrivalDateTime = arrivalDateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final StopType other = (StopType) obj;
        return Objects.equal(this.airport, other.airport) && Objects.equal(this.duration, other.duration) && Objects
            .equal(this.arrivalDateTime, other.arrivalDateTime);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.airport);
        result = 31 * result + Objects.hashCode(this.duration);
        result = 31 * result + Objects.hashCode(this.arrivalDateTime);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("airport", airport).add("duration", duration)
            .add("arrivalDateTime", arrivalDateTime).toString();
    }

}