// Generated by eBay Common SDK Platform
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * 乘客类型：成人/儿童/婴儿
 */
@XmlType(name = "TravelerCategoryCodeEnum")
@XmlEnum
@SuppressWarnings("all")
public enum TravelerCategoryCodeEnum {

    @XmlEnumValue("ADT") ADT(0, "ADT"),

    @XmlEnumValue("CHD") CHD(1, "CHD"),

    @XmlEnumValue("INF") INF(2, "INF");

    private final int intValue;
    private final String value;

    TravelerCategoryCodeEnum(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static TravelerCategoryCodeEnum fromValue(String v) {
        for (TravelerCategoryCodeEnum e : TravelerCategoryCodeEnum.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static TravelerCategoryCodeEnum findByValue(int value) {
        switch (value) {
            case 0:
                return ADT;
            case 1:
                return CHD;
            case 2:
                return INF;
            default:
                return null;
        }
    }
}