// Generated by eBay Common SDK Platform
package contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * 航程类型
 */
@XmlType(name = "TripTypeCodeEnum")
@XmlEnum
@SuppressWarnings("all")
public enum TripTypeCodeEnum {

    @XmlEnumValue("OW") OW(0, "OW"),

    @XmlEnumValue("RT") RT(1, "RT"),

    @XmlEnumValue("MT") MT(2, "MT");

    private final int intValue;
    private final String value;

    TripTypeCodeEnum(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static TripTypeCodeEnum fromValue(String v) {
        for (TripTypeCodeEnum e : TripTypeCodeEnum.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static TripTypeCodeEnum findByValue(int value) {
        switch (value) {
            case 0:
                return OW;
            case 1:
                return RT;
            case 2:
                return MT;
            default:
                return null;
        }
    }
}