/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.bookingvalidation.v1;

import contract.commontype.v1.ErrorResultType;
import contract.commontype.v1.ResultStatusEnumType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookabilityInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", propOrder = {
    "bookabilityStatus", "flightInfoList", "errorResult"})
@SuppressWarnings("all")
public class BookabilityInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public BookabilityInfoType(ResultStatusEnumType bookabilityStatus, List<FlightInfoType> flightInfoList,
        ErrorResultType errorResult) {
        this.bookabilityStatus = bookabilityStatus;
        this.flightInfoList = flightInfoList;
        this.errorResult = errorResult;
    }

    public BookabilityInfoType() {
        this.bookabilityStatus = ResultStatusEnumType.values()[0];
    }

    @JsonProperty("BookabilityStatus")
    @XmlElement(name = "BookabilityStatus")
    private ResultStatusEnumType bookabilityStatus;

    @JsonProperty("FlightInfoList")
    @XmlElement(name = "FlightInfo")
    @XmlElementWrapper(name = "FlightInfoList")
    private List<FlightInfoType> flightInfoList;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult", nillable = true)
    private ErrorResultType errorResult;

    /**
     * 验舱状态：成功，失败，拦截，处理中
     */
    public ResultStatusEnumType getBookabilityStatus() {
        return this.bookabilityStatus;
    }

    public void setBookabilityStatus(ResultStatusEnumType bookabilityStatus) {
        this.bookabilityStatus = bookabilityStatus;
    }

    /**
     * 验舱信息列表
     */
    public List<FlightInfoType> getFlightInfoList() {
        return this.flightInfoList;
    }

    public void setFlightInfoList(List<FlightInfoType> flightInfoList) {
        this.flightInfoList = flightInfoList;
    }

    /**
     * 验舱单独错误信息
     */
    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final BookabilityInfoType other = (BookabilityInfoType) obj;
        return Objects.equal(this.bookabilityStatus, other.bookabilityStatus) && Objects
            .equal(this.flightInfoList, other.flightInfoList) && Objects.equal(this.errorResult, other.errorResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.bookabilityStatus);
        result = 31 * result + Objects.hashCode(this.flightInfoList);
        result = 31 * result + Objects.hashCode(this.errorResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("bookabilityStatus", bookabilityStatus)
            .add("flightInfoList", flightInfoList).add("errorResult", errorResult).toString();
    }

}