/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", elementFormDefault = XmlNsForm.QUALIFIED)
package contract.bookingvalidation.v1;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
