/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.bookingvalidation.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 实收币种价格
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaidPriceType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", propOrder = {
    "salePrice", "tax", "publishPrice", "currency"})
@SuppressWarnings("all")
public class PaidPriceType implements Serializable {

    private static final long serialVersionUID = 1L;

    public PaidPriceType(double salePrice, double tax, double publishPrice, String currency) {
        this.salePrice = salePrice;
        this.tax = tax;
        this.publishPrice = publishPrice;
        this.currency = currency;
    }

    public PaidPriceType() {
    }

    @JsonProperty("SalePrice")
    @XmlElement(name = "SalePrice")
    private double salePrice;

    @JsonProperty("Tax")
    @XmlElement(name = "Tax")
    private double tax;

    @JsonProperty("PublishPrice")
    @XmlElement(name = "PublishPrice")
    private double publishPrice;

    @JsonProperty("Currency")
    @XmlElement(name = "Currency")
    private String currency;

    /**
     * *携程卖价
     */
    public double getSalePrice() {
        return this.salePrice;
    }

    public void setSalePrice(double salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * *税费
     */
    public double getTax() {
        return this.tax;
    }

    public void setTax(double tax) {
        this.tax = tax;
    }

    /**
     * *航空公司卖价
     */
    public double getPublishPrice() {
        return this.publishPrice;
    }

    public void setPublishPrice(double publishPrice) {
        this.publishPrice = publishPrice;
    }

    /**
     * 实收币种
     */
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final PaidPriceType other = (PaidPriceType) obj;
        return Objects.equal(this.salePrice, other.salePrice) && Objects.equal(this.tax, other.tax) && Objects
            .equal(this.publishPrice, other.publishPrice) && Objects.equal(this.currency, other.currency);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.salePrice);
        result = 31 * result + Objects.hashCode(this.tax);
        result = 31 * result + Objects.hashCode(this.publishPrice);
        result = 31 * result + Objects.hashCode(this.currency);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("salePrice", salePrice).add("tax", tax)
            .add("publishPrice", publishPrice).add("currency", currency).toString();
    }

}