/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.bookingvalidation.v1;

import contract.commontype.v1.BaggageInfoType;
import contract.commontype.v1.TravelerCategoryCodeEnum;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QteDetailInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", propOrder = {
    "travelerCategoryCode", "priceChanged", "paidPrice", "baggageList", "priceExtend"})
@SuppressWarnings("all")
public class QteDetailInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public QteDetailInfoType(TravelerCategoryCodeEnum travelerCategoryCode, boolean priceChanged,
        PaidPriceType paidPrice, List<BaggageInfoType> baggageList, String priceExtend) {
        this.travelerCategoryCode = travelerCategoryCode;
        this.priceChanged = priceChanged;
        this.paidPrice = paidPrice;
        this.baggageList = baggageList;
        this.priceExtend = priceExtend;
    }

    public QteDetailInfoType() {
        this.travelerCategoryCode = TravelerCategoryCodeEnum.values()[0];
    }

    @JsonProperty("TravelerCategoryCode")
    @XmlElement(name = "TravelerCategoryCode")
    private TravelerCategoryCodeEnum travelerCategoryCode;

    @JsonProperty("PriceChanged")
    @XmlElement(name = "PriceChanged")
    private boolean priceChanged;

    @JsonProperty("PaidPrice")
    @XmlElement(name = "PaidPrice")
    private PaidPriceType paidPrice;

    @JsonProperty("BaggageList")
    @XmlElement(name = "BaggageInfo", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:commontype:v1")
    @XmlElementWrapper(name = "BaggageList")
    private List<BaggageInfoType> baggageList;

    @JsonProperty("PriceExtend")
    @XmlElement(name = "PriceExtend")
    private String priceExtend;

    /**
     * 乘客类型
     */
    public TravelerCategoryCodeEnum getTravelerCategoryCode() {
        return this.travelerCategoryCode;
    }

    public void setTravelerCategoryCode(TravelerCategoryCodeEnum travelerCategoryCode) {
        this.travelerCategoryCode = travelerCategoryCode;
    }

    /**
     * 是否变价
     */
    public boolean getPriceChanged() {
        return this.priceChanged;
    }

    public void setPriceChanged(boolean priceChanged) {
        this.priceChanged = priceChanged;
    }

    /**
     * 实收币种价格
     */
    public PaidPriceType getPaidPrice() {
        return this.paidPrice;
    }

    public void setPaidPrice(PaidPriceType paidPrice) {
        this.paidPrice = paidPrice;
    }

    public List<BaggageInfoType> getBaggageList() {
        return this.baggageList;
    }

    public void setBaggageList(List<BaggageInfoType> baggageList) {
        this.baggageList = baggageList;
    }

    /**
     * 价格扩展字段，商旅渠道使用
     *                         示例：{\"publishprice\":5050,\"accountprice\":5050,\"originalpublishprice\":5050,\"originalaccountprice\":5050,\"originalsaleprice\":5050,\"originaltax\":948}
     */
    public String getPriceExtend() {
        return this.priceExtend;
    }

    public void setPriceExtend(String priceExtend) {
        this.priceExtend = priceExtend;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final QteDetailInfoType other = (QteDetailInfoType) obj;
        return Objects.equal(this.travelerCategoryCode, other.travelerCategoryCode) && Objects
            .equal(this.priceChanged, other.priceChanged) && Objects.equal(this.paidPrice, other.paidPrice) && Objects
            .equal(this.baggageList, other.baggageList) && Objects.equal(this.priceExtend, other.priceExtend);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.travelerCategoryCode);
        result = 31 * result + Objects.hashCode(this.priceChanged);
        result = 31 * result + Objects.hashCode(this.paidPrice);
        result = 31 * result + Objects.hashCode(this.baggageList);
        result = 31 * result + Objects.hashCode(this.priceExtend);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("travelerCategoryCode", travelerCategoryCode)
            .add("priceChanged", priceChanged).add("paidPrice", paidPrice).add("baggageList", baggageList)
            .add("priceExtend", priceExtend).toString();
    }

}