/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.bookingvalidation.v1;

import contract.commontype.v1.ErrorResultType;
import contract.commontype.v1.ResultStatusEnumType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepricingInfoType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", propOrder = {
    "repricingStatus", "qteDetailInfoList", "errorResult"})
@SuppressWarnings("all")
public class RepricingInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public RepricingInfoType(ResultStatusEnumType repricingStatus, List<QteDetailInfoType> qteDetailInfoList,
        ErrorResultType errorResult) {
        this.repricingStatus = repricingStatus;
        this.qteDetailInfoList = qteDetailInfoList;
        this.errorResult = errorResult;
    }

    public RepricingInfoType() {
        this.repricingStatus = ResultStatusEnumType.values()[0];
    }

    @JsonProperty("RepricingStatus")
    @XmlElement(name = "RepricingStatus")
    private ResultStatusEnumType repricingStatus;

    @JsonProperty("QteDetailInfoList")
    @XmlElement(name = "QteDetailInfo")
    @XmlElementWrapper(name = "QteDetailInfoList")
    private List<QteDetailInfoType> qteDetailInfoList;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult", nillable = true)
    private ErrorResultType errorResult;

    /**
     * 验价状态：成功，失败，拦截，处理中
     */
    public ResultStatusEnumType getRepricingStatus() {
        return this.repricingStatus;
    }

    public void setRepricingStatus(ResultStatusEnumType repricingStatus) {
        this.repricingStatus = repricingStatus;
    }

    /**
     * 验价信息列表
     */
    public List<QteDetailInfoType> getQteDetailInfoList() {
        return this.qteDetailInfoList;
    }

    public void setQteDetailInfoList(List<QteDetailInfoType> qteDetailInfoList) {
        this.qteDetailInfoList = qteDetailInfoList;
    }

    /**
     * 验价单独错误信息
     */
    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final RepricingInfoType other = (RepricingInfoType) obj;
        return Objects.equal(this.repricingStatus, other.repricingStatus) && Objects
            .equal(this.qteDetailInfoList, other.qteDetailInfoList) && Objects
            .equal(this.errorResult, other.errorResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.repricingStatus);
        result = 31 * result + Objects.hashCode(this.qteDetailInfoList);
        result = 31 * result + Objects.hashCode(this.errorResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("repricingStatus", repricingStatus)
            .add("qteDetailInfoList", qteDetailInfoList).add("errorResult", errorResult).toString();
    }

}