/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.bookingvalidation.v1;

import contract.commontype.v1.ErrorResultType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 验舱验价结果
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationResultType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:bookingvalidation:v1", propOrder = {
    "priceUnitIndex", "tokenNumber", "repricingInfo", "bookabilityInfo", "errorResult"})
@SuppressWarnings("all")
public class ValidationResultType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ValidationResultType(int priceUnitIndex, String tokenNumber, RepricingInfoType repricingInfo,
        BookabilityInfoType bookabilityInfo, ErrorResultType errorResult) {
        this.priceUnitIndex = priceUnitIndex;
        this.tokenNumber = tokenNumber;
        this.repricingInfo = repricingInfo;
        this.bookabilityInfo = bookabilityInfo;
        this.errorResult = errorResult;
    }

    public ValidationResultType() {
    }

    @JsonProperty("PriceUnitIndex")
    @XmlElement(name = "PriceUnitIndex")
    private int priceUnitIndex;

    @JsonProperty("TokenNumber")
    @XmlElement(name = "TokenNumber")
    private String tokenNumber;

    @JsonProperty("RepricingInfo")
    @XmlElement(name = "RepricingInfo")
    private RepricingInfoType repricingInfo;

    @JsonProperty("BookabilityInfo")
    @XmlElement(name = "BookabilityInfo")
    private BookabilityInfoType bookabilityInfo;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult", nillable = true)
    private ErrorResultType errorResult;

    /**
     * PU索引
     */
    public int getPriceUnitIndex() {
        return this.priceUnitIndex;
    }

    public void setPriceUnitIndex(int priceUnitIndex) {
        this.priceUnitIndex = priceUnitIndex;
    }

    /**
     * 验舱验价Token
     */
    public String getTokenNumber() {
        return this.tokenNumber;
    }

    public void setTokenNumber(String tokenNumber) {
        this.tokenNumber = tokenNumber;
    }

    /**
     * 验价详细信息
     */
    public RepricingInfoType getRepricingInfo() {
        return this.repricingInfo;
    }

    public void setRepricingInfo(RepricingInfoType repricingInfo) {
        this.repricingInfo = repricingInfo;
    }

    /**
     * 验舱详细信息
     */
    public BookabilityInfoType getBookabilityInfo() {
        return this.bookabilityInfo;
    }

    public void setBookabilityInfo(BookabilityInfoType bookabilityInfo) {
        this.bookabilityInfo = bookabilityInfo;
    }

    /**
     * 单票错误信息, Token获取结果失败时赋值
     */
    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final ValidationResultType other = (ValidationResultType) obj;
        return Objects.equal(this.priceUnitIndex, other.priceUnitIndex) && Objects
            .equal(this.tokenNumber, other.tokenNumber) && Objects.equal(this.repricingInfo, other.repricingInfo)
            && Objects.equal(this.bookabilityInfo, other.bookabilityInfo) && Objects
            .equal(this.errorResult, other.errorResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.priceUnitIndex);
        result = 31 * result + Objects.hashCode(this.tokenNumber);
        result = 31 * result + Objects.hashCode(this.repricingInfo);
        result = 31 * result + Objects.hashCode(this.bookabilityInfo);
        result = 31 * result + Objects.hashCode(this.errorResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("priceUnitIndex", priceUnitIndex).add("tokenNumber", tokenNumber)
            .add("repricingInfo", repricingInfo).add("bookabilityInfo", bookabilityInfo).add("errorResult", errorResult)
            .toString();
    }

}