/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.simplereservation.v1;

import contract.commontype.v1.ErrorResultType;
import contract.commontype.v1.ReservationResultType;
import contract.commontype.v1.ResultStatusEnumType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 简化订位结果
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleReservationResultType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:simplereservation:v1", propOrder = {
    "priceUnitIndex", "tokenNumber", "resultStatus", "reservationResult", "errorResult"})
@SuppressWarnings("all")
public class SimpleReservationResultType implements Serializable {

    private static final long serialVersionUID = 1L;

    public SimpleReservationResultType(int priceUnitIndex, String tokenNumber, ResultStatusEnumType resultStatus,
        ReservationResultType reservationResult, ErrorResultType errorResult) {
        this.priceUnitIndex = priceUnitIndex;
        this.tokenNumber = tokenNumber;
        this.resultStatus = resultStatus;
        this.reservationResult = reservationResult;
        this.errorResult = errorResult;
    }

    public SimpleReservationResultType() {
        this.resultStatus = ResultStatusEnumType.values()[0];
    }

    @JsonProperty("PriceUnitIndex")
    @XmlElement(name = "PriceUnitIndex")
    private int priceUnitIndex;

    @JsonProperty("TokenNumber")
    @XmlElement(name = "TokenNumber")
    private String tokenNumber;

    @JsonProperty("ResultStatus")
    @XmlElement(name = "ResultStatus")
    private ResultStatusEnumType resultStatus;

    @JsonProperty("ReservationResult")
    @XmlElement(name = "ReservationResult")
    private ReservationResultType reservationResult;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult")
    private ErrorResultType errorResult;

    /**
     * PU索引
     */
    public int getPriceUnitIndex() {
        return this.priceUnitIndex;
    }

    public void setPriceUnitIndex(int priceUnitIndex) {
        this.priceUnitIndex = priceUnitIndex;
    }

    /**
     * 订位Token
     */
    public String getTokenNumber() {
        return this.tokenNumber;
    }

    public void setTokenNumber(String tokenNumber) {
        this.tokenNumber = tokenNumber;
    }

    /**
     * 订位状态（SUCCESS:成功，FAIL:失败放过，INTERCEPTED:拦截，IN_PROCESS:处理中）
     */
    public ResultStatusEnumType getResultStatus() {
        return this.resultStatus;
    }

    public void setResultStatus(ResultStatusEnumType resultStatus) {
        this.resultStatus = resultStatus;
    }

    /**
     * 成功结果
     */
    public ReservationResultType getReservationResult() {
        return this.reservationResult;
    }

    public void setReservationResult(ReservationResultType reservationResult) {
        this.reservationResult = reservationResult;
    }

    /**
     * 错误结果
     */
    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final SimpleReservationResultType other = (SimpleReservationResultType) obj;
        return Objects.equal(this.priceUnitIndex, other.priceUnitIndex) && Objects
            .equal(this.tokenNumber, other.tokenNumber) && Objects.equal(this.resultStatus, other.resultStatus)
            && Objects.equal(this.reservationResult, other.reservationResult) && Objects
            .equal(this.errorResult, other.errorResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.priceUnitIndex);
        result = 31 * result + Objects.hashCode(this.tokenNumber);
        result = 31 * result + Objects.hashCode(this.resultStatus);
        result = 31 * result + Objects.hashCode(this.reservationResult);
        result = 31 * result + Objects.hashCode(this.errorResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("priceUnitIndex", priceUnitIndex).add("tokenNumber", tokenNumber)
            .add("resultStatus", resultStatus).add("reservationResult", reservationResult)
            .add("errorResult", errorResult).toString();
    }

}