/**
 * Autogenerated by soa-sdk-toolkit
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package contract.simplereservation.v1;

import contract.commontype.v1.ErrorResultType;
import contract.commontype.v1.ResponseHeaderType;
import contract.commontype.v1.ResultStatusEnumType;
import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SimpleReservationResponse", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:simplereservation:v1")
@XmlType(name = "SimpleReservationResponseType", namespace = "urn:com:ctrip:flight:intl:booking:bookingValidation:contract:simplereservation:v1", propOrder = {
    "responseStatus", "responseHeader", "tokenNumber", "resultStatus", "simpleReservationResultList", "errorResult"})
@SuppressWarnings("all")
public class SimpleReservationResponseType implements HasResponseStatus, Serializable {

    private static final long serialVersionUID = 1L;

    public SimpleReservationResponseType(ResponseStatusType responseStatus, ResponseHeaderType responseHeader,
        String tokenNumber, ResultStatusEnumType resultStatus,
        List<SimpleReservationResultType> simpleReservationResultList, ErrorResultType errorResult) {
        this.responseStatus = responseStatus;
        this.responseHeader = responseHeader;
        this.tokenNumber = tokenNumber;
        this.resultStatus = resultStatus;
        this.simpleReservationResultList = simpleReservationResultList;
        this.errorResult = errorResult;
    }

    public SimpleReservationResponseType() {
        this.resultStatus = ResultStatusEnumType.values()[0];
    }

    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @JsonProperty("ResponseHeader")
    @XmlElement(name = "ResponseHeader")
    private ResponseHeaderType responseHeader;

    @JsonProperty("TokenNumber")
    @XmlElement(name = "TokenNumber")
    private String tokenNumber;

    @JsonProperty("ResultStatus")
    @XmlElement(name = "ResultStatus")
    private ResultStatusEnumType resultStatus;

    @JsonProperty("SimpleReservationResultList")
    @XmlElement(name = "SimpleReservationResult", nillable = true)
    @XmlElementWrapper(name = "SimpleReservationResultList")
    private List<SimpleReservationResultType> simpleReservationResultList;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult")
    private ErrorResultType errorResult;

    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    public ResponseHeaderType getResponseHeader() {
        return this.responseHeader;
    }

    public void setResponseHeader(ResponseHeaderType responseHeader) {
        this.responseHeader = responseHeader;
    }

    /**
     * 订位Token
     */
    public String getTokenNumber() {
        return this.tokenNumber;
    }

    public void setTokenNumber(String tokenNumber) {
        this.tokenNumber = tokenNumber;
    }

    /**
     * 订位状态（SUCCESS:成功，FAIL:失败放过，INTERCEPTED:拦截，IN_PROCESS:处理中）
     */
    public ResultStatusEnumType getResultStatus() {
        return this.resultStatus;
    }

    public void setResultStatus(ResultStatusEnumType resultStatus) {
        this.resultStatus = resultStatus;
    }

    public List<SimpleReservationResultType> getSimpleReservationResultList() {
        return this.simpleReservationResultList;
    }

    public void setSimpleReservationResultList(List<SimpleReservationResultType> simpleReservationResultList) {
        this.simpleReservationResultList = simpleReservationResultList;
    }

    /**
     * 总错误结果
     */
    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final SimpleReservationResponseType other = (SimpleReservationResponseType) obj;
        return Objects.equal(this.responseStatus, other.responseStatus) && Objects
            .equal(this.responseHeader, other.responseHeader) && Objects.equal(this.tokenNumber, other.tokenNumber)
            && Objects.equal(this.resultStatus, other.resultStatus) && Objects
            .equal(this.simpleReservationResultList, other.simpleReservationResultList) && Objects
            .equal(this.errorResult, other.errorResult);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.responseHeader);
        result = 31 * result + Objects.hashCode(this.tokenNumber);
        result = 31 * result + Objects.hashCode(this.resultStatus);
        result = 31 * result + Objects.hashCode(this.simpleReservationResultList);
        result = 31 * result + Objects.hashCode(this.errorResult);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("responseStatus", responseStatus)
            .add("responseHeader", responseHeader).add("tokenNumber", tokenNumber).add("resultStatus", resultStatus)
            .add("simpleReservationResultList", simpleReservationResultList).add("errorResult", errorResult).toString();
    }

}